# Site-wide settings. Restart `jekyll serve` after editing this file.

# Site Settings
locale                   : "en-US"
title                    : "Taijie Chen"
title_separator          : "·"
name                     : &name "Taijie Chen"
description              : &description "Ph.D. candidate at the University of Hong Kong, working on artificial intelligence for next-generation mobility systems."
url                      : https://chentaijie98.github.io
baseurl                  : ""
repository               : "chentaijie98/chentaijie98.github.io"
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
comments:
  provider               : false
atom_feed:
  path                   :

# SEO
google_site_verification :
bing_site_verification   :

# Social sharing
twitter:
  username               :
og_image                 : /images/profile.jpg
social:
  type                   : Person
  name                   : *name

# Analytics
analytics:
  provider               : false

# Site author
author:
  name             : *name
  bio              : "Ph.D. Candidate, The University of Hong Kong"
  location         : "Hong Kong SAR, China"
  email            : "ctj21@connect.hku.hk"
  googlescholar    : "https://scholar.google.com/citations?user=ELY31RgAAAAJ"
  researchgate     : "https://www.researchgate.net/profile/Taijie_Chen2"
  github           : "chentaijie98"


# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - .bundle
  - .jekyll-cache
  - .localgems
  - .preview
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - node_modules
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/


# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: article
  - scope:
      path: ""
      type: teaching
    values:
      layout: article


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed


# Outputting
permalink: /:categories/:title/
timezone: Asia/Hong_Kong


# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
whitelist:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jemoji
